#ifndef DEFS_H
#define DEFS_H

#define SCREEN_WIDTH 1280
#define SCREEN_HEIGHT 720

#define FPS 60
#define GRAVITY 9.81f

#define FRAME_DELAY (1000 / FPS)
#define JUMP_FORCE -12.25f
#define FALL_MULTIPLIER 3.5f
#define PLAYER_ANGLE_MULTIPLIER 3.5f
#define PLAYER_TEXTURE_WIDTH 100
#define PLAYER_TEXTURE_HEIGHT 64
#define PLAYER_HITBOX_LEFT_OFFSET 35
#define PLAYER_HITBOX_RIGHT_OFFSET 10
#define PLAYER_HITBOX_TOP_BOTTOM_OFFSET 10
#define PIPE_SPEED 5
#define PIPE_WIDTH 150
#define BASE_PIPE_GAP 200

#define BACKGROUND_VOLUME_LEVEL 10

#endif
